branch-defaults:
  master:
    environment: flask-env
    group_suffix: null
environment-defaults:
  flask-env:
    branch: null
    repository: null
global:
  application_name: perch-flask
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: perch
  repository: null
  sc: git
  workspace_type: Application
